import { Schema, model } from "mongoose";
import { IArrears } from "../types";
import { generateDisplayId } from "../utils/generateId";

/**
 * Manually-entered arrears (opening / carried-forward dues) for a customer.
 * Distinct from `Bill.remainingBalance` (which is arrears generated by the
 * billing flow itself) — this is for amounts an admin types in directly,
 * e.g. a balance carried over from before this system was used.
 *
 * `remainingArrears` mirrors the Advance module's `remainingAdvance` pattern:
 * it starts equal to `amount` and is zeroed out once the amount has been
 * folded into a customer's bill (see consumeArrearsForCustomer in
 * arrears.controller.ts), so it is never counted twice.
 */
const ArrearsSchema = new Schema<IArrears>(
  {
    displayId: { type: String, unique: true, default: () => generateDisplayId("ARR") },
    customerId: { type: Schema.Types.ObjectId, ref: "Customer", required: true },
    amount: { type: Number, required: true, min: 0 },
    remainingArrears: { type: Number, required: true, min: 0 },
    date: { type: Date, default: Date.now },
    remarks: { type: String, default: "" },
  },
  { timestamps: { createdAt: true, updatedAt: false } },
);

export default model<IArrears>("Arrears", ArrearsSchema);
